# Generated by Django 5.0.2 on 2024-02-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
